// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"TerraxLighting","status":true,"description":"v1.5.0 Creates an extra layer that darkens a map and adds lightsources!","parameters":{"Player radius":"300","Add to options":"Yes","Option menu entry":"Lighting effects","Reset Lights":"No","Save DaynightHours":"10","Save DaynightMinutes":"0","Save DaynightSeconds":"0","Flashlight offset":"0","Screensize X":"1750","Screensize Y":"1400","Kill Switch":"No"}}
];
